name: Metrics
on:
  schedule: [{cron: "0 16 * * *" }]
  push: {branches: ["main"]}
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 🧣 create metrics
        uses: lowlighter/metrics@latest
        with:
          # Gist
          output_action: gist
          committer_gist: ${{ secrets.GIST }}

          # Configs
          filename: profile_metrics.svg
          token: ${{ secrets.TOKEN }}
          config_timezone: Asia/Seoul
          template: classic
          base: header, activity, community

          # IsoCalendar
          plugin_isocalendar: no
          #plugin_isocalendar_duration: full-year

          # Achievements
          plugin_achievements: no
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          # Lines
          plugin_lines: no

          # Introduction
          plugin_introduction: yes
          plugin_introduction_title: yes

          # Traffic
          plugin_traffic: yes

          # Notable
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_indepth: yes
          plugin_notable_filter: stars:>5

          # Wakatime
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_languages_other: no
