name: Metrics
on:
  schedule: [{ cron: "0 16 */3 * *" }]
  push: { branches: [main] }
  workflow_dispatch:

jobs:
  keepalive:
    name: keep workflow alive
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: create metrics
        uses: lowlighter/metrics@latest
        with:
          # Gist
          output_action: gist
          committer_gist: ${{ vars.GIST }}

          # Configs
          filename: profile_metrics.svg
          token: ${{ secrets.TOKEN }}
          config_padding: 0, 60%
          config_timezone: Asia/Seoul
          template: classic
          base: header

          # Notable
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_indepth: yes
          plugin_notable_filter: stars:>5
          plugin_notable_skipped: Cata-Rogall-Modpack
